### ISSUE TITLE
Can a sub branch sequence function added into this extension?

### ISSUE THREAD

**Issue by xianggithubli** [Pjaerr/Code-Flow-Extension#22]
Can a sub branch sequence function added into this extension?

**Comment by Pjaerr** [comment]
@xianggithubli I think it is definitely possible, I believe the challenge would be in displaying that sub branch at the end when we generate the diagram.

**Comment by Pjaerr** [comment]
@xianggithubli If you wanted to have a go at implementing this I am happy to help!

**Comment by Pjaerr** [comment]
I will be rebuilding this extension from scratch to make it actually useful. @xianggithubli if you have any ideas of what you'd like out of an extension like this then please don't hesitate to let me know!
