### ISSUE TITLE
command 'extension.codeflow' not found

### ISSUE THREAD

**Issue by hvsharma63** [Pjaerr/Code-Flow-Extension#23]
![image](https://user-images.githubusercontent.com/19151036/67547594-25b14e80-f71d-11e9-8b49-caf741118c69.png)

After Installing the extension, the above error came. If you've any solution, please let me know. I very much liked the idea of the extension and would like to use this anyhow. :)
IDE: VS Code

**Comment by Pjaerr** [comment]
That's weird I don't get this issue, I'll look into it, thanks for making me aware!

**Comment by AndresReyesE** [comment]
I have had the same issue since I tried this extension months ago. Have the same issue right now.

**Comment by Pjaerr** [comment]
Hi @AndresReyesE  & @hvsharma63  could you please open up the extension in your extensions viewer and go to Contributions and send me a screenshot?

EG:
![image](https://user-images.githubusercontent.com/11336751/69245021-fff15b00-0b9d-11ea-80c5-1094ad976f73.png)

**Comment by Pjaerr** [comment]
I have tried to reproduce this issue on both my computer and on a friends machine and I can't do it.

You guys could try uninstalling the extension and then navigating to `C:\Users\YOUR_USER\.vscode\extensions\` (on windows) and then deleting the `joshjackson.code-flow-extension-1.1.1` folder and then reinstalling it from the marketplace.

Let me know if the above works for you!

@hvsharma63 @AndresReyesE

**Comment by AndresReyesE** [comment]
Good morning, here is the screenshot you asked for.

![Contributions screen](https://user-images.githubusercontent.com/48465914/69349739-e99adc00-0c3d-11ea-92dd-450a7f0bac86.png)

However, after accessing the Command Palette (Ctrl + Shift + P) and clicking over the CodeFlow option, this is always the result

![image](https://user-images.githubusercontent.com/48465914/69349965-57470800-0c3e-11ea-9e97-3cca3b7cb12b.png)

I am going to attach the information about my VSCode in case it is useful for you
![image](https://user-images.githubusercontent.com/48465914/69350046-76459a00-0c3e-11ea-9294-4a3591512749.png)


I have already tried manually deleting the folder you specify, it uninstalls the extension successfully, but when I install it again the error persists.
Another heads up, this happens in both Linux and Windows for me.

**Comment by Pjaerr** [comment]
> Good morning, here is the screenshot you asked for.
> 
> ![Contributions screen](https://user-images.githubusercontent.com/48465914/69349739-e99adc00-0c3d-11ea-92dd-450a7f0bac86.png)
> 
> However, after accessing the Command Palette (Ctrl + Shift + P) and clicking over the CodeFlow option, this is always the result
> 
> ![image](https://user-images.githubusercontent.com/48465914/69349965-57470800-0c3e-11ea-9e97-3cca3b7cb12b.png)
> 
> I am going to attach the information about my VSCode in case it is useful for you
> ![image](https://user-images.githubusercontent.com/48465914/69350046-76459a00-0c3e-11ea-9294-4a3591512749.png)
> 
> I have already tried manually deleting the folder you specify, it uninstalls the extension successfully, but when I install it again the error persists.
> Another heads up, this happens in both Linux and Windows for me.

Hmm I am really not sure why this is happening as I have tested on multiple machines and it has worked everytime. I don't currently have the time to properly look into this but I will leave the issue open in case I do in the future.

Sorry that you can't use the extension!

Thanks for your screenshots :)

**Comment by lisai1004** [comment]
Hi.

I upgrade vscode to newest version(1.57.1) and it works ok on the Windows10.The version info is the following.
Tut using the version SSL to connect a remote workspace which is on the ubuntu. the issue already exsits.
```
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by Pjaerr** [comment]
👋 Hey all, if you're looking for an extension similar to this but a million times better, an extension has recently been released called Grok (https://www.trygrok.com/) which might be what you're looking for.

Given how advanced Grok is, I probably won't rebuild this extension anymore, thanks for taking an interest though!

**Comment by curtisbelt** [comment]
I just wanted to let you know this issue is alive and well - I just tried to use your extension and it happens to me.

![image](https://user-images.githubusercontent.com/4251760/234960326-6382fb84-05d5-44e3-9bd2-e231adfbc318.png)

It must be something about your extension code for this bug to survive over 3 years 🤔

Wishing you luck, I saw your comment acknowledging Grok is gone and that you're considering restarting development on this extension!

**Comment by ubless607** [comment]
@Pjaerr It works on Windows, but not over ssh connection.

**Comment by AmirNaghibi** [comment]
@Pjaerr 

>  Hey all, if you're looking for an extension similar to this but a million times better, an extension has recently been released called Grok (https://www.trygrok.com/) which might be what you're looking for.

the link is broken. Do you know how else I can download `grok` for vscode?

**Comment by Pjaerr** [comment]
👋  Hey @AmirNaghibi yep it looks like the creator of grok has removed the extension completely! There's an issue in this repo exploring rebuilding this extension properly so it's useful but I can't say I'll be working on it anytime soon: https://github.com/Pjaerr/Code-Flow-Extension/issues/45#issuecomment-1519093719
