### ISSUE TITLE
Remove mention of Grok in README

### ISSUE THREAD

**Issue by Nezteb** [Pjaerr/Code-Flow-Extension#41]
Grok seemed to have disappeared:
- https://web.archive.org/web/20210812070223/https://www.trygrok.com/
- https://web.archive.org/web/20210705001921/https://marketplace.visualstudio.com/items?itemName=Adaptilab.grok

Now the original URL redirects to spam/phishing content. 😅 

That being said, your extension looks awesome and I'd love to contribute. I've wanted a tool like this for a long time.

**Comment by Pjaerr** [comment]
😬 Ah thanks for mentioning. It's probably a good thing as I have wanted to rebuild this extension properly for a while but lost motivation as Grok looked way better 😅

I'll remove mention of it this week.
